version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Installing yarn pkg mgr
          command: |
            npm install yarn
      - run:
          name: Installing npm packages
          command: |
            yarn install
      - run:
          name: Build running
          command: |
            CI=true yarn build

workflows:
  version: 2.1
  all_builds:
    jobs:
      - build
